---
include:
  - project: 'pipeline-components/org/config'
    ref: master
    file: pipeline.yml

test amd64:
  variables:
    BUILD_ARCH: amd64
  extends: .test
  script:
    - docker run --rm "${CI_REGISTRY_IMAGE}/build:${BUILD_ARCH}-${CI_COMMIT_SHA}" checkov --version

test amd64 defaultcmd:
  variables:
    BUILD_ARCH: amd64
  extends: .test
  script:
    - docker run --rm "${CI_REGISTRY_IMAGE}/build:${BUILD_ARCH}-${CI_COMMIT_SHA}" --version

test amd64 testterraform:
  rules:
    allow_failure: true
  variables:
    BUILD_ARCH: amd64
  extends: .test
  script:
    - docker run --rm "${CI_REGISTRY_IMAGE}/build:${BUILD_ARCH}-${CI_COMMIT_SHA}" -f test.tf
